use_frameworks!
inhibit_all_warnings!

target 'ButlerExample-iOS' do
  platform :ios, '10.0'

  pod 'Butler', path: '../', inhibit_warnings: false

  target 'ButlerExample-iOSTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

target 'ButlerExample-macOS' do
  platform :osx, '10.10'

  pod 'Butler', path: '../', inhibit_warnings: false

  target 'ButlerExample-macOSTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
